controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    front_wheel_steer_position_controller:
      type: position_controllers/JointGroupPositionController

    left_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

# Individual controller parameters
front_wheel_steer_position_controller:
  ros__parameters:
    joints:
      - front_steer_joint
    command_interfaces:
      - position

left_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
    command_interfaces:
      - velocity

right_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_wheel_joint
    command_interfaces:
      - velocity